# yaml-language-server: http://json.schemastore.org/prettierrc
trailingComma: all
useTabs: true
semi: true
endOfLine: lf
overrides:
  - files:
      - tsconfig.json
      - "apps/*/tsconfig.json"
      - "etc/*/tsconfig.json"
      - "libs/*/tsconfig.json"
    options:
      parser: json-stringify
