$schema: "https://moonrepo.dev/schemas/tasks.json"

tasks:
  serve:
    command: trunk serve
    local: true
  mkTarget:
    command: mkdir -p target/apps
  build:
    command: trunk
    args:
      - --no-color
      - build
    env:
      # trunk doesn't support NO_COLOR=1
      NO_COLOR: "true"
    inputs:
      - src/**/*
      - "*.html"
      - "*.toml"
    deps:
      - mkTarget
