$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  serve:
    command: trunk serve
    preset: server
  mkTarget:
    command: mkdir -p target/apps
  build:
    script: env -u NO_COLOR trunk build
    toolchain: system
    inputs:
      - src/**/*
      - "*.html"
      - "*.toml"
    deps:
      - mkTarget
inheritedBy:
  tag: trunk
