$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  serve:
    command: trunk serve
    preset: server
  mkTarget:
    command: mkdir -p target/apps
  build:
    command: trunk
    args:
      - --no-color
      - build
    env:
      NO_COLOR: "true"
    inputs:
      - src/**/*
      - "*.html"
      - "*.toml"
    deps:
      - mkTarget
inheritedBy:
  tag: trunk
