$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  syncpack-lint:
    toolchain: node
    preset: utility
    script: syncpack lint --dependency-types prod,dev
    options:
      runFromWorkspaceRoot: true
  syncpack-fix:
    toolchain: node
    preset: utility
    script: syncpack fix
    options:
      runFromWorkspaceRoot: true
  syncpack-format:
    toolchain: node
    preset: utility
    script: syncpack format
    options:
      runFromWorkspaceRoot: true
inheritedBy:
  tag: syncpack
