name: Deploy Dev

on:
  push:
    branches: ["main"]

jobs:
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dagger
        uses: dagger/dagger-for-github@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Call script
        working-directory: ./scripts/ci
        run: ./release-dev.ts
        env:
          MODE: "dev"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_DEV }}
