name: Build and publish to production branch

on:
  push:
    branches: ["master"]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build and test
        run: |
          yarn build

      - name: Publish
        run: |
          yarn publish
