name: Release Prod

on:
  push:
    tags:
      - v*.*.*

jobs:
  run-workflow:
    name: Run Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.18.9
          verb: functions
          workdir: ./etc/runner

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - name: Run workflow
        working-directory: ./etc/scripts/workflows
        run: ./release.ts
        env:
          MODE: prod
          GH_TOKEN: ${{ secrets.GH_TOKEN_PROD }}
