name: Release Dev

on:
  push:
    branches:
      - main

jobs:
  call-function:
    name: Call function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/init.yml

      - name: Call script
        working-directory: ./scripts/pipelines
        run: ./release.ts
        env:
          MODE: "dev"
          GH_TOKEN: ${{ secrets.GH_TOKEN_DEV }}
