name: Release Stg

on:
  push:
    branches:
      - release-*

jobs:
  run-workflow:
    name: Run Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.18.9
          verb: functions
          workdir: ./etc/workflow-runtime

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - name: Run workflow
        working-directory: ./etc/scripts/workflows
        run: ./release.ts
        env:
          MODE: stg
          GH_TOKEN: ${{ secrets.GH_TOKEN_STG }}
